---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION=2.3.1.0
cache: bundler
#sudo: false
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
  - sudo apt-get install -qq wget
  - sudo apt-get install -qq virtualbox
  - sudo apt-get install -qq virtualbox-dkms virtualbox-ose-dkms
  - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.3_x86_64.deb
  - sudo dpkg -i vagrant_1.6.3_x86_64.deb
install:
  # Install Ansible.
  - sudo pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  #- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  - sudo pip install https://github.com/diyan/pywinrm/archive/df049454a9309280866e0156805ccda12d71c93a.zip --upgrade

script:
  - sudo ansible --version
  - export ANSIBLE_ROLES_PATH="../"
  - echo localhost > inventory
  - sudo vagrant --version
  - sudo VBoxManage --version
  - sudo vagrant up
  - sudo ansible-playbook -i inventory --syntax-check windows.yml
  - sudo ansible-playbook -i inventory --connection=local --sudo -vvvv windows.yml
